version: "3.9"

services:
  # MongoDB para Order Service
  mongo-order:
    image: mongo:6.0
    container_name: mongo-order
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: eventify-2025
      MONGO_INITDB_DATABASE: order-db
    volumes:
      - mongo-order-data:/data/db

  # MongoDB para Auth Service
  mongo-auth:
    image: mongo:6.0
    container_name: mongo-auth
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: eventify-2025
      MONGO_INITDB_DATABASE: authdb
    volumes:
      - mongo-auth-data:/data/db

  # MongoDB para Notification Service
  mongo-notification:
    image: mongo:6.0
    container_name: mongo-notification
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: eventify-2025
      MONGO_INITDB_DATABASE: notificationdb
    volumes:
      - mongo-notification-data:/data/db

volumes:
  mongo-order-data:
  mongo-auth-data:
  mongo-notification-data:
