version: "3.9"

services:
  mongo-order:
    image: mongo:6.0
    container_name: mongo-order
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: orderdb
    volumes:
      - mongo-order-data:/data/db

  mongo-auth:
    image: mongo:6.0
    container_name: mongo-auth
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: authdb
    volumes:
      - mongo-auth-data:/data/db

  mongo-notification:
    image: mongo:6.0
    container_name: mongo-notification
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: notificationdb
    volumes:
      - mongo-notification-data:/data/db

volumes:
  mongo-order-data:
  mongo-auth-data:
  mongo-notification-data:
