sonar.projectKey=Eventify
sonar.projectName=Eventify EDA
sonar.host.url=http://localhost:9000
sonar.login=sqp_5e7c6c66f0a258ee5d634bd27b9274124f690d94

# Global configurations
sonar.sources=package.json
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.test.ts,**/coverage/**,**/jest.config.ts
sonar.javascript.lcov.reportPaths=services/*/coverage/lcov.info,libs/*/coverage/lcov.info
sonar.typescript.lcov.reportPaths=services/*/coverage/lcov.info,libs/*/coverage/lcov.info

# Monorepo configuration
sonar.modules=auth-service,inventory-service,notification-service,order-service,payment-service,qualification-service,kafka-lib

# Auth Service
auth-service.sonar.projectBaseDir=services/eventify-auth-service
auth-service.sonar.sources=src
auth-service.sonar.tests=test
auth-service.sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
auth-service.sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/jest.config.ts

# Inventory Service
inventory-service.sonar.projectBaseDir=services/eventify-inventory-service
inventory-service.sonar.sources=src
inventory-service.sonar.tests=tests
inventory-service.sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
inventory-service.sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/jest.config.ts

# Notification Service
notification-service.sonar.projectBaseDir=services/eventify-notification-service
notification-service.sonar.sources=src
notification-service.sonar.tests=test
notification-service.sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
notification-service.sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/jest.config.ts

# Order Service
order-service.sonar.projectBaseDir=services/eventify-order-service
order-service.sonar.sources=src
order-service.sonar.tests=test
order-service.sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
order-service.sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/jest.config.ts

# Payment Service
payment-service.sonar.projectBaseDir=services/eventify-payment-service
payment-service.sonar.sources=src
payment-service.sonar.tests=test
payment-service.sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
payment-service.sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/jest.config.ts

# Qualification Service
qualification-service.sonar.projectBaseDir=services/eventify-qualification-service
qualification-service.sonar.sources=src
qualification-service.sonar.tests=test
qualification-service.sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
qualification-service.sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/jest.config.ts

# Kafka Library
kafka-lib.sonar.projectBaseDir=libs/kafka
kafka-lib.sonar.sources=src
kafka-lib.sonar.tests=src
kafka-lib.sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
kafka-lib.sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/jest.config.ts